name: wasm
version: '0.1'
author: Stephen Diehl
maintainer: stephen.m.diehl@gmail.com
license: MIT
extra-source-files:
- README.md
- src/Language/Wasm/Parser.y
- src/Language/Wasm/Lexer.x
build-tools:
- alex >=3.1.3
- happy >=1.9.4
dependencies:
- base >=4.6 && <5.0

library:
  source-dirs: src
  ghc-options:
  - -Wwarn
  - -fwarn-incomplete-patterns
  - -fwarn-unused-imports
  exposed-modules:
  - Language.Wasm.Core
  - Language.Wasm.Pretty
  - Language.Wasm.Syntax
  - Language.Wasm.Binary
  - Language.Wasm.Lexer
  - Language.Wasm.Parser
  - Language.Wasm.Entry
  other-modules:
  - Language.Wasm.Monad
  - Language.Wasm.Position
  dependencies:
  - array                >= 0.5  && <0.6
  - text                 >= 1.1
  - bytestring           >= 0.10
  - mtl                  >= 2.2  && <3.0
  - transformers         >= 0.4  && <0.6
  - pretty               >= 1.1  && <1.2
  - pretty-show          >= 1.6  && <1.7
  - process              >= 1.1
  - directory            >= 1.2 
  - containers           >= 0.5  && <0.6
  - binary               >= 0.7  && <0.9
  - cereal               >= 0.4  && <0.6
  - ansi-wl-pprint       >= 0.6  && <0.7
  - wl-pprint-text       >= 1.0  && <2.0
  - optparse-applicative >= 0.11 && <0.15
  - pretty-hex           >= 0.1

executables:
  wasm:
    main: Main.hs
    source-dirs: exec
    dependencies:
    - wasm ==0.1

tests:
  test:
    main: Test.hs
    source-dirs: tests
    dependencies:
    - wasm ==0.1
    - filepath >=1.3 && <1.5
    - text >=1.1 && <1.3
    - bytestring >=0.10 && <0.11
    - cereal >=0.4 && <0.6
    - tasty >=0.7
    - tasty-hunit >=0.4.1 && <0.10
    - tasty-golden >=2.2 && <2.4
    - pretty-hex >= 0.1
    - mtl ==2.2.1
